import SideBar from '@/components/sideBar'
import Slider from '@/components/slider'
import TopBar from '@/components/topBar'
import Head from 'next/head'




export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TopBar />
        <SideBar />
        <Slider />
      </main>
    </>
  )
}
